name: Notifier for New Switch Releases

on:
  schedule:
    - cron: "*/15 * * * *"   # toutes les 15 minutes
  workflow_dispatch: {}

jobs:
  run-notifier:
    runs-on: ubuntu-latest

    steps:
      # Checkout main pour le code
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Récupérer seen_releases.json depuis la branche datas
      - name: Get seen_releases.json from datas
        run: |
          git checkout origin/datas -- seen_releases.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Discord notifier
        env:
          DISCORD_WEBHOOK: ${{ secrets.Releases_new_switch_TOKEN }}
        run: |
          python main.py

      # Commit seen_releases.json sur la branche datas
      - name: Push seen_releases.json to datas
        run: |
          git stash -- seen_releases.json
          git checkout datas
          git stash pop
          git add seen_releases.json
          git diff --cached --quiet && exit 0
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "Update seen_releases.json"
          git push origin datas
